"""State schema for the PowerShell command execution workflow."""

from typing import TypedDict, Annotated, Literal, Optional, List, Dict, Any
from operator import add
from datetime import datetime


class CommandState(TypedDict):
    """
    Complete state schema for the PowerShell command execution workflow.

    Uses Annotated types with reducer functions to handle state updates.
    The `add` operator allows appending to lists without overwriting previous values.
    """

    # User Input Phase
    user_input: str  # Original natural language request
    session_id: str  # Unique session identifier
    timestamp: datetime  # Request timestamp

    # Command Generation Phase
    generated_command: Optional[str]  # PowerShell command generated by LLM
    command_explanation: Optional[str]  # LLM explanation of what command does
    safety_assessment: Optional[Dict[str, Any]]  # Safety analysis results
    shell_type: Optional[Literal["powershell", "cmd", "bash"]]  # Which shell to use
    attempted_shells: Annotated[List[str], add]  # Track which shells we've tried

    # Confirmation Phase
    user_confirmed: Optional[bool]  # User approval/rejection
    confirmation_timestamp: Optional[datetime]
    user_feedback: Optional[str]  # Optional user comments

    # Execution Phase
    execution_status: Literal[
        "pending", "executing", "success",
        "failed", "cancelled", "error"
    ]
    execution_result: Optional[Dict[str, Any]]  # stdout, stderr, return_code
    execution_timestamp: Optional[datetime]

    # Validation Phase
    validation_passed: Optional[bool]  # LLM validation result
    validation_reasoning: Optional[str]  # Why validation passed/failed
    validation_suggestions: Optional[List[str]]  # Suggestions for improvements

    # Error Handling
    error_message: Optional[str]  # Any error that occurred
    error_type: Optional[str]  # Error category
    retry_count: int  # Number of retries attempted
    max_retries: int  # Maximum retries allowed
    auto_retry_count: int  # Number of automatic retry attempts
    max_auto_retries: int  # Maximum auto-retries allowed
    failure_analysis: Optional[Dict[str, Any]]  # LLM analysis of failure
    failed_attempts: Annotated[List[Dict[str, Any]], add]  # History of failed attempts

    # History and Context (using reducer for appending)
    messages: Annotated[List[Dict[str, Any]], add]  # Conversation history
    execution_history: Annotated[List[Dict[str, Any]], add]  # Past commands executed
    conversation_messages: Optional[List[Dict[str, str]]]  # Previous conversation context for LLM

    # Analysis Phase (for content understanding)
    requires_analysis: Optional[bool]  # Whether user wants content analysis
    analysis_type: Optional[str]  # Type of analysis: purpose, security, explain, etc.
    analysis_target: Optional[str]  # File path or content to analyze
    analysis_result: Optional[Dict[str, Any]]  # LLM analysis output
    content_to_analyze: Optional[str]  # Actual content extracted from files/output

    # Flow Control
    next_step: Optional[Literal[
        "generate", "confirm", "execute",
        "validate", "present", "retry", "try_alternative", "analyze", "end"
    ]]
